export const GET_SITE_SETTINGS = "GET_SITE_SETTINGS";
export const GET_SERVICE = "GET_SERVICES";
export const GET_SUPPORTERS = "GET_SUPPORTERS";
export const GET_SLIDERS = "GET_SLIDERS";
export const GET_EVENTS = "GET_EVENTS";
export const GET_PUBLIC_PRODUCTS = "GET_PUBLIC_PRODUCTS";
export const TEAMS = "TEAMS";
//CART
export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART";
export const CLEAR_ITEMS_FROM_CART = "CLEAR_ITEMS_FROM_CART";
export const CLEAR_ALL_ITEMS_FROM_CART = "CLEAR_ALL_ITEMS_FROM_CART";
export const CHECKOUT="CHECKOUT";

export const ORDER_PRODUCT = "ORDER_PRODUCT";
export const ORDER_HISTORY = "ORDER_HISTORY";
// REGISTER
export const REGISTER = "REGISTER";
export const GET_MEMBERSHIP = "GET_MEMBERSHIP";
// LOGIN 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const SUCCESS_UPDATE_PASSWORD = "SUCCESS_UPDATE_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const SUCCESS_FORGOT_PASSWORD = "SUCCESS_FORGOT_PASSWORD";
// LOGIN USER
export const GET_PRIVATE_PRODUCTS = "GET_PRIVATE_PRODUCTS";
// Loader

export const OPEN_LOADER = "OPEN_LOADER";
export const CLOSE_LOADER = "CLOSE_LOADER";
export const FETCH_PAST_COMMITTEE = "FETCH_PAST_COMMITTEE";
